"""create_disciplines_table

Revision ID: 62f206feeeb8
Revises: 1d21c92d177d
Create Date: 2026-09-18 19:29:51.220598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f206feeeb8'
down_revision: Union[str, None] = '1d21c92d177d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.Enum('MAJOR', 'MEDIUM', name='discipline_tier'), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('chat_url', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.telegram_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_disciplines_admin_id'), 'disciplines', ['admin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disciplines_admin_id'), table_name='disciplines')
    op.drop_table('disciplines')
    # ### end Alembic commands ###
